version: 2

project_name: caelum

before:
  hooks:
    - rustup default stable
    - bash -c 'command -v cross &>/dev/null || cargo install cross'
    - cargo fmt --all -- --check
    - cargo clippy --all-features -- -D warnings
    - cargo test --all
    - cargo test --all --all-features
    - cargo test --all --no-default-features
    - cargo publish --manifest-path crates/caelum-build/Cargo.toml --dry-run --allow-dirty
    - cargo publish --dry-run --allow-dirty

builds:
  - id: caelum-linux-amd64-v2
    builder: rust
    command: build
    tool: ./scripts/cargo-or-cross.py
    binary: debug
    targets:
      - x86_64-unknown-linux-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v2

  - id: caelum-linux-amd64-v3
    builder: rust
    command: build
    tool: ./scripts/cargo-or-cross.py
    binary: debug
    targets:
      - x86_64-unknown-linux-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v3

  - id: caelum-linux-arm64
    builder: rust
    command: build
    tool: ./scripts/cargo-or-cross.py
    binary: debug
    targets:
      - aarch64-unknown-linux-gnu
    flags:
      - --release
      - --all-features

  - id: caelum-linux-armv7
    builder: rust
    command: build
    tool: ./scripts/cargo-or-cross.py
    binary: debug
    targets:
      - armv7-unknown-linux-gnueabihf
    flags:
      - --release
      - --all-features

  - id: caelum-windows-amd64-v2
    builder: rust
    command: build
    tool: ./scripts/cargo-or-cross.py
    binary: debug
    targets:
      - x86_64-pc-windows-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v2

  - id: caelum-windows-amd64-v3
    builder: rust
    command: build
    tool: ./scripts/cargo-or-cross.py
    binary: debug
    targets:
      - x86_64-pc-windows-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v3

source:
  enabled: false

common_archive_files: &common_archive_files
  - LICENSE
  - README.md

archives:
  - id: linux-amd64-v2
    ids:
      - caelum-linux-amd64-v2
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64_v2"
    formats:
      - tar.gz
    files: *common_archive_files

  - id: linux-amd64-v3
    ids:
      - caelum-linux-amd64-v3
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64_v3"
    formats:
      - tar.gz
    files: *common_archive_files

  - id: linux-arm64
    ids:
      - caelum-linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_arm64"
    formats:
      - tar.gz
    files: *common_archive_files

  - id: linux-armv7
    ids:
      - caelum-linux-armv7
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_armv7"
    formats:
      - tar.gz
    files: *common_archive_files

  - id: windows-amd64-v2
    ids:
      - caelum-windows-amd64-v2
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64_v2"
    formats:
      - zip
    files: *common_archive_files

  - id: windows-amd64-v3
    ids:
      - caelum-windows-amd64-v3
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64_v3"
    formats:
      - zip
    files: *common_archive_files

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: Sn0wo2
    name: caelum
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
