version: 2

project_name: caelum

before:
  hooks:
    - rustup default stable
    - cargo install cross
    - cargo fmt --all -- --check
    - cargo clippy --all-features -- -D warnings
    - cargo test --all
    - cargo test --all --all-features
    - cargo test --all --no-default-features
    - cargo publish --manifest-path crates/caelum-build/Cargo.toml --dry-run --allow-dirty
    - cargo publish --dry-run --allow-dirty

builds:
  - id: caelum-linux-amd64-v2
    builder: rust
    command: build
    tool: cross
    binary: caelum
    targets:
      - x86_64-unknown-linux-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v2

  - id: caelum-linux-amd64-v3
    builder: rust
    command: build
    tool: cross
    binary: caelum
    targets:
      - x86_64-unknown-linux-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v3

  - id: caelum-linux-arm64
    builder: rust
    command: build
    tool: cross
    binary: caelum
    targets:
      - aarch64-unknown-linux-gnu
    flags:
      - --release
      - --all-features

  - id: caelum-linux-armv7
    builder: rust
    command: build
    tool: cross
    binary: caelum
    targets:
      - armv7-unknown-linux-gnueabihf
    flags:
      - --release
      - --all-features

  - id: caelum-windows-amd64-v2
    builder: rust
    command: build
    tool: cross
    binary: caelum
    targets:
      - x86_64-pc-windows-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v2

  - id: caelum-windows-amd64-v3
    builder: rust
    command: build
    tool: cross
    binary: caelum
    targets:
      - x86_64-pc-windows-gnu
    flags:
      - --release
      - --all-features
    env:
      - RUSTFLAGS=-C target-cpu=x86-64-v3

source:
  enabled: false

archives:
  - id: linux
    ids:
      - caelum-linux-amd64-v2
      - caelum-linux-amd64-v3
      - caelum-linux-arm64
      - caelum-linux-armv7
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md
      - config.toml
      - config.schema.json

  - id: windows
    ids:
      - caelum-windows-amd64-v2
      - caelum-windows-amd64-v3
    formats:
      - zip
    files:
      - LICENSE
      - README.md
      - config.toml
      - config.schema.json

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: Sn0wo2
    name: caelum
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
