name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-gnu,aarch64-unknown-linux-gnu,armv7-unknown-linux-gnueabihf

      - name: Install rust-src
        shell: bash
        run: rustup component add rust-src

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: caelum-cargo
          cache-on-failure: true

      - name: Cache cross
        uses: actions/cache@v5
        with:
          path: ~/.cargo/bin/cross
          key: ${{ runner.os }}-cargo-tool-cross-v1

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          install-only: true

      - name: Install cross
        run: |
          if ! command -v cross &> /dev/null; then
            cargo install cross
          fi

      - name: Prepare scripts
        run: chmod +x ./scripts/cargo-or-cross.py

      - name: Build
        run: goreleaser build --snapshot --clean --skip=before --config .goreleaser.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: caelum-builds
          path: dist/*
          retention-days: 7
